#### Builidng AI agents with huggingface smolagents
This notebook covers chapter 2 (first coding exercise of the building AI agents with huggingface smolagents course) [here](https://learn.deeplearning.ai/courses/building-code-agents-with-hugging-face-smolagents/lesson/tv10w/introduction-to-code-agents)

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import os
import io
import IPython.display
from PIL import Image
import base64

In [3]:
from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

In [4]:
from helpers import get_huggingface_token, get_openai_api_key

In [5]:
get_huggingface_token()

'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'

In [6]:
from huggingface_hub import login
login(token=get_huggingface_token())

In [8]:
import pandas as pd

suppliers_data =  {
    "name": [
        "Montreal Ice Cream Co",
        "Brain Freeze Brothers",
        "Toronto Gelato Ltd",
        "Buffalo Scoops",
        "Vermont Creamery",
    ],
    "location": [
        "Montreal, QC",
        "Burlington, VT",
        "Toronto, ON",
        "Buffalo, NY",
        "Portland, ME",
    ],
    "distance_km": [120, 85, 400, 220, 280],
    "canadian": [True, False, True, False, False],
    "price_per_liter": [1.95, 1.91, 1.82, 2.43, 2.33],
    "tasting_fee": [0, 12.50, 30.14, 42.00, 0.20],
}

data_description = """Suppliers have an additional tasting fee: that is a fixed fee applied to each order to taste the ice cream."""
suppliers_df = pd.DataFrame(suppliers_data)
suppliers_df

,name,location,distance_km,canadian,price_per_liter,tasting_fee
0,Montreal Ice Cream Co,"Montreal, QC",120,True,1.95,0.00
1,Brain Freeze Brothers,"Burlington, VT",85,False,1.91,12.50
2,Toronto Gelato Ltd,"Toronto, ON",400,True,1.82,30.14
3,Buffalo Scoops,"Buffalo, NY",220,False,2.43,42.00
4,Vermont Creamery,"Portland, ME",280,False,2.33,0.20

In [9]:
import numpy as np

def calculate_daily_supplier_price(row):
    order_volume = 30

    # Calculate raw product cost
    product_cost = row["price_per_liter"] * order_volume

    # Calculate transport cost
    trucks_needed = np.ceil(order_volume / 300)
    cost_per_km = 1.20
    transport_cost = row["distance_km"] * cost_per_km * trucks_needed

    # Calculate tariffs for ice cream imported from Canada
    tariff = product_cost * np.pi / 50 * row["canadian"]

    # Get total cost
    total_cost = product_cost + transport_cost + tariff + row["tasting_fee"]
    return total_cost

suppliers_df["daily_price"] = suppliers_df.apply(calculate_daily_supplier_price, axis=1)
display(suppliers_df)

# Let's remove this column now.
suppliers_df = suppliers_df.drop("daily_price", axis=1)

,name,location,distance_km,canadian,price_per_liter,tasting_fee,daily_price
0,Montreal Ice Cream Co,"Montreal, QC",120,True,1.95,0.00,206.175663
1,Brain Freeze Brothers,"Burlington, VT",85,False,1.91,12.50,171.800000
2,Toronto Gelato Ltd,"Toronto, ON",400,True,1.82,30.14,568.170619
3,Buffalo Scoops,"Buffalo, NY",220,False,2.43,42.00,378.900000
4,Vermont Creamery,"Portland, ME",280,False,2.33,0.20,406.100000

In [10]:
# First we make a few tools
from smolagents import tool

@tool
def calculate_transport_cost(distance_km: float, order_volume: float) -> float:
    """
    Calculate transportation cost based on distance and order size.
    Refrigerated transport costs $1.2 per kilometer and has a capacity of 300 liters.

    Args:
        distance_km: the distance in kilometers
        order_volume: the order volume in liters
    """
    trucks_needed = np.ceil(order_volume / 300)
    cost_per_km = 1.20
    return distance_km * cost_per_km * trucks_needed


@tool
def calculate_tariff(base_cost: float, is_canadian: bool) -> float:
    """
    Calculates tariff for Canadian imports. Returns the tariff only, not the total cost.
    Assumes tariff on dairy products from Canada is worth 2 * pi / 100, approx 6.2%

    Args:
        base_cost: the base cost of goods, not including transportation cost.
        is_canadian: wether the import is from Canada.
    """
    if is_canadian:
        return base_cost * np.pi / 50
    return 0

In [11]:
calculate_transport_cost.description

'Calculate transportation cost based on distance and order size.\nRefrigerated transport costs $1.2 per kilometer and has a capacity of 300 liters.'

In [12]:
calculate_transport_cost.name

'calculate_transport_cost'

#### Setup the model to be use for the agent
We would be making use of the Qwen models to power our agents

In [13]:
from smolagents import HfApiModel, CodeAgent

model = HfApiModel(
    "Qwen/Qwen2.5-72B-Instruct",
    provider="together",
    max_tokens=4096,
    temperature=0.1,
)

code_agent = CodeAgent(model=model, 
tools=[calculate_transport_cost, calculate_tariff],
max_steps=10, 
additional_authorized_imports=["numpy", "pandas"],
verbosity_level=2)


code_agent.logger.console.width = 66

In [14]:
code_agent.run("""Can you get me the transportation cost for 50 liters
    of ice cream over 10 kilometers?""")

╭─────────────────────────── New run ────────────────────────────╮
│                                                                │
│ Can you get me the transportation cost for 50 liters           │
│     of ice cream over 10 kilometers?                           │
│                                                                │
╰─ HfApiModel - Qwen/Qwen2.5-72B-Instruct ───────────────────────╯

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Output message of the LLM: ───────────────────────────────────────
Thought: I will use the `calculate_transport_cost` tool to get the
transportation cost for 50 liters of ice cream over 10 kilometers.
Code:
```py
transport_cost = calculate_transport_cost(distance_km=10,
order_volume=50)
print(transport_cost)
```<end_code>

 ─ Executing parsed code: ───────────────────────────────────────
  transport_cost = calculate_transport_cost(distance_km=10,
  order_volume=50)
  print(transport_cost)
 ────────────────────────────────────────────────────────────────

Execution logs:
12.0

Out: None

[Step 1: Duration 1.60 seconds| Input tokens: 2,240 | Output
tokens: 64]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Output message of the LLM: ───────────────────────────────────────
Thought: The transportation cost for 50 liters of ice cream over
10 kilometers is 12.0. I will now provide the final answer.
Code:
```py
final_answer(12.0)
```<end_code>

 ─ Executing parsed code: ───────────────────────────────────────
  final_answer(12.0)
 ────────────────────────────────────────────────────────────────

Out - Final answer: 12.0

[Step 2: Duration 1.22 seconds| Input tokens: 4,638 | Output
tokens: 115]

12.0

In [15]:
task = """Here is a dataframe of different ice cream suppliers.
Could you give me a comparative table (as a dataframe) of the total
daily price for getting daily ice cream delivery from each of them,
given that we need exactly 30 liters of ice cream per day? Take
into account transportation cost and tariffs.
"""

code_agent.logger.level = 1 # Lower verbosity level
code_agent.run(
    task,
    additional_args={"suppliers_data": suppliers_df, "data_description": data_description},
)

╭─────────────────────────── New run ────────────────────────────╮
│                                                                │
│ Here is a dataframe of different ice cream suppliers.          │
│ Could you give me a comparative table (as a dataframe) of the  │
│ total                                                          │
│ daily price for getting daily ice cream delivery from each of  │
│ them,                                                          │
│ given that we need exactly 30 liters of ice cream per day?     │
│ Take                                                           │
│ into account transportation cost and tariffs.                  │
│                                                                │
│ You have been provided with these additional arguments, that   │
│ you can access using the keys as variables in your python      │
│ code:                                                          │
│ {'suppliers_data':                     name        location    │
│ distance_km  canadian  \                                       │
│ 0  Montreal Ice Cream Co    Montreal, QC          120          │
│ True                                                           │
│ 1  Brain Freeze Brothers  Burlington, VT           85          │
│ False                                                          │
│ 2     Toronto Gelato Ltd     Toronto, ON          400          │
│ True                                                           │
│ 3         Buffalo Scoops     Buffalo, NY          220          │
│ False                                                          │
│ 4       Vermont Creamery    Portland, ME          280          │
│ False                                                          │
│                                                                │
│    price_per_liter  tasting_fee                                │
│ 0             1.95         0.00                                │
│ 1             1.91        12.50                                │
│ 2             1.82        30.14                                │
│ 3             2.43        42.00                                │
│ 4             2.33         0.20  , 'data_description':         │
│ 'Suppliers have an additional tasting fee: that is a fixed fee │
│ applied to each order to taste the ice cream.'}.               │
│                                                                │
╰─ HfApiModel - Qwen/Qwen2.5-72B-Instruct ───────────────────────╯

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 ─ Executing parsed code: ───────────────────────────────────────
  import pandas as pd

  # Convert the suppliers_data dictionary to a dataframe
  suppliers_df = pd.DataFrame(suppliers_data)

  # Calculate the total cost for each supplier
  def calculate_total_cost(row):
      # Calculate the cost of the ice cream
      ice_cream_cost = row['price_per_liter'] * 30
      # Calculate the transportation cost
      transport_cost =
  calculate_transport_cost(distance_km=row['distance_km'],
  order_volume=30)
      # Calculate the tariff
      tariff = calculate_tariff(base_cost=ice_cream_cost +
  transport_cost, is_canadian=row['canadian'])
      # Calculate the total cost
      total_cost = ice_cream_cost + transport_cost + tariff +
  row['tasting_fee']
      return total_cost

  # Apply the function to each row of the dataframe
  suppliers_df['total_daily_price'] =
  suppliers_df.apply(calculate_total_cost, axis=1)

  # Create a new dataframe with the total daily price for each
  supplier
  comparative_table = suppliers_df[['name',
  'total_daily_price']]
  print(comparative_table)
 ────────────────────────────────────────────────────────────────

Execution logs:
                    name  total_daily_price
0  Montreal Ice Cream Co         215.223450
1  Brain Freeze Brothers         171.800000
2     Toronto Gelato Ltd         598.329909
3         Buffalo Scoops         378.900000
4       Vermont Creamery         406.100000

Out: None

[Step 1: Duration 10.42 seconds| Input tokens: 2,517 | Output
tokens: 282]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 ─ Executing parsed code: ───────────────────────────────────────
  final_answer(comparative_table)
 ────────────────────────────────────────────────────────────────

Out - Final answer:                     name  total_daily_price
0  Montreal Ice Cream Co         215.223450
1  Brain Freeze Brothers         171.800000
2     Toronto Gelato Ltd         598.329909
3         Buffalo Scoops         378.900000
4       Vermont Creamery         406.100000

[Step 2: Duration 1.78 seconds| Input tokens: 5,720 | Output
tokens: 329]

                    name  total_daily_price
0  Montreal Ice Cream Co         215.223450
1  Brain Freeze Brothers         171.800000
2     Toronto Gelato Ltd         598.329909
3         Buffalo Scoops         378.900000
4       Vermont Creamery         406.100000

#### Comparing to traditional tool calling
This is how a traditional tool calling agent would handle said problem

Thought: I need to use the `calculate_transport_cost` tool
to get the transportation cost for 50 liters of ice cream over
10 kilometers.
                        
Code:
```py                                  
transport_cost = calculate_transport_cost(
    distance_km=10,
    order_volume=50
)
print(transport_cost)                             
```

Thought: I need to use the `calculate_transport_cost` tool
to get the transportation cost for 50 liters of ice cream over
10 kilometers.
                        
Code:
```py                                  
transport_cost = calculate_transport_cost(
    distance_km=10,
    order_volume=50
)
print(transport_cost)                             
```

In [16]:
from smolagents import ToolCallingAgent

model = HfApiModel(
    "Qwen/Qwen2.5-72B-Instruct",
    temperature=0.6
)
agent = ToolCallingAgent(
    model=model,
    tools=[calculate_transport_cost, calculate_tariff],
    max_steps=20,
)
agent.logger.console.width=66

In [17]:
output = agent.run(
    task,
    additional_args={"suppliers_data": suppliers_df, "data_description": data_description},
)
print(output)

╭─────────────────────────── New run ────────────────────────────╮
│                                                                │
│ Here is a dataframe of different ice cream suppliers.          │
│ Could you give me a comparative table (as a dataframe) of the  │
│ total                                                          │
│ daily price for getting daily ice cream delivery from each of  │
│ them,                                                          │
│ given that we need exactly 30 liters of ice cream per day?     │
│ Take                                                           │
│ into account transportation cost and tariffs.                  │
│                                                                │
│ You have been provided with these additional arguments, that   │
│ you can access using the keys as variables in your python      │
│ code:                                                          │
│ {'suppliers_data':                     name        location    │
│ distance_km  canadian  \                                       │
│ 0  Montreal Ice Cream Co    Montreal, QC          120          │
│ True                                                           │
│ 1  Brain Freeze Brothers  Burlington, VT           85          │
│ False                                                          │
│ 2     Toronto Gelato Ltd     Toronto, ON          400          │
│ True                                                           │
│ 3         Buffalo Scoops     Buffalo, NY          220          │
│ False                                                          │
│ 4       Vermont Creamery    Portland, ME          280          │
│ False                                                          │
│                                                                │
│    price_per_liter  tasting_fee                                │
│ 0             1.95         0.00                                │
│ 1             1.91        12.50                                │
│ 2             1.82        30.14                                │
│ 3             2.43        42.00                                │
│ 4             2.33         0.20  , 'data_description':         │
│ 'Suppliers have an additional tasting fee: that is a fixed fee │
│ applied to each order to taste the ice cream.'}.               │
│                                                                │
╰─ HfApiModel - Qwen/Qwen2.5-72B-Instruct ───────────────────────╯

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

╭────────────────────────────────────────────────────────────────╮
│ Calling tool: 'calculate_transport_cost' with arguments:       │
│ {'distance_km': 120, 'order_volume': 30}                       │
╰────────────────────────────────────────────────────────────────╯

Observations: 144.0

[Step 1: Duration 2.00 seconds| Input tokens: 1,762 | Output
tokens: 32]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
The JSON blob you used is invalid

[Step 2: Duration 0.64 seconds| Input tokens: 3,631 | Output
tokens: 35]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 3 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

╭────────────────────────────────────────────────────────────────╮
│ Calling tool: 'calculate_transport_cost' with arguments:       │
│ {'distance_km': 120, 'order_volume': 30}                       │
╰────────────────────────────────────────────────────────────────╯

Observations: 144.0

[Step 3: Duration 7.97 seconds| Input tokens: 5,544 | Output
tokens: 67]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 4 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

╭────────────────────────────────────────────────────────────────╮
│ Calling tool: 'calculate_transport_cost' with arguments:       │
│ {'distance_km': 85, 'order_volume': 30}                        │
╰────────────────────────────────────────────────────────────────╯

Observations: 102.0

[Step 4: Duration 8.06 seconds| Input tokens: 7,560 | Output
tokens: 98]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 5 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
The JSON blob you used is invalid

[Step 5: Duration 0.79 seconds| Input tokens: 9,680 | Output
tokens: 101]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 6 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734d-382467431bf1cb5813c1a6cc;c23ee9cf-b41f-49ed-964f-f
eb03ddb59af)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 6: Duration 0.17 seconds| Input tokens: 11,800 | Output
tokens: 104]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 7 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734d-6fe029803aae64263399a4df;45192543-2433-4a96-a333-e
76cc24b14bf)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 7: Duration 0.20 seconds| Input tokens: 13,920 | Output
tokens: 107]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 8 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734d-0f6be6ce719b0f3d3098db24;8405b5a0-5acc-48df-9b0c-0
ab7468d8fb9)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 8: Duration 0.55 seconds| Input tokens: 16,040 | Output
tokens: 110]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 9 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734e-33793a82027eddae1a4d60b6;4931c65a-9139-4687-b90d-6
2e179c91f1d)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 9: Duration 0.16 seconds| Input tokens: 18,160 | Output
tokens: 113]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 10 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734e-13bb55be42869cc16bea9b17;333f6ff0-db1f-404c-9203-c
8f96c634965)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 10: Duration 0.17 seconds| Input tokens: 20,280 | Output
tokens: 116]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 11 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734e-0e1eaa800f6348ff6a3f954d;3f5e9dab-6f4f-43e4-958c-8
c3f8a1ee126)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 11: Duration 0.15 seconds| Input tokens: 22,400 | Output
tokens: 119]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 12 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734e-7760124f423646c2048bd5aa;f181fef0-b834-418c-89ab-1
3340b7bd63c)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 12: Duration 0.16 seconds| Input tokens: 24,520 | Output
tokens: 122]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 13 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734f-2a10907409b3e5536cf86ac6;efdaefe7-e9aa-4f81-bdd0-9
51f7aeeb285)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 13: Duration 0.20 seconds| Input tokens: 26,640 | Output
tokens: 125]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 14 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734f-08e1b239480d211c1d8a60d9;a8d676cd-eb3f-4786-8135-5
b4bbb4f7776)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 14: Duration 0.18 seconds| Input tokens: 28,760 | Output
tokens: 128]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 15 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734f-274fa0c16e9eb3ea33c8e3cb;f972fce2-601c-40c9-bfa9-d
2287a8778e8)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 15: Duration 0.18 seconds| Input tokens: 30,880 | Output
tokens: 131]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 16 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734f-47e78ef65750365a236d43ca;31aacf1f-24b1-4574-9de7-a
6b8dbbb9365)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 16: Duration 0.16 seconds| Input tokens: 33,000 | Output
tokens: 134]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 17 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734f-2fa5b53d5c8fc5542129c62f;d5ff903a-4c21-4bf8-8419-e
374a92dc97d)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 17: Duration 0.16 seconds| Input tokens: 35,120 | Output
tokens: 137]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 18 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-6846734f-1ef72aeb108f791820c32332;45442e95-5ccd-49d2-a223-1
35bb1b6a073)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 18: Duration 0.17 seconds| Input tokens: 37,240 | Output
tokens: 140]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 19 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-68467350-1f84797d4b7b27ca0dbeaceb;aa92e515-6cb0-4e2a-a9e8-7
620a5ee8790)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 19: Duration 0.16 seconds| Input tokens: 39,360 | Output
tokens: 143]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 20 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error while generating or parsing output:
402 Client Error: Payment Required for url:
https://router.huggingface.co/together/v1/chat/completions
(Request ID:
Root=1-68467350-66992b343d0b5f6d77fb92e1;1cf45cf9-5e1b-4ce0-a0ea-2
1b5b0ad1e07)

You have exceeded your monthly included credits for Inference
Providers. Subscribe to PRO to get 20x more monthly included
credits.

[Step 20: Duration 0.16 seconds| Input tokens: 41,480 | Output
tokens: 146]

Reached max steps.

[Step 21: Duration 0.38 seconds| Input tokens: 43,600 | Output
tokens: 149]

Error in generating final LLM output:
402 Client Error: Payment Required for url: https://router.huggingface.co/together/v1/chat/completions (Request ID: Root=1-68467350-389f943e282fed93136fc64a;6f53c292-0767-4527-9051-49bc57c0131a)

You have exceeded your monthly included credits for Inference Providers. Subscribe to PRO to get 20x more monthly included credits.